title: CuriousWorld
description: Fascinating Science & Facts
baseurl: "/auto-content-site"
url: "https://ysnslk.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown


