name: Build and Deploy Jekyll Site

on:
  schedule:
    - cron: '0 8 * * *'  # her gün 08:00 UTC'de
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby for Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Jekyll and Bundler
        run: gem install jekyll bundler

      - name: Install Python and dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests

      - name: Generate Markdown content
        run: python content_generator.py

      - name: Build Jekyll site
        run: jekyll build

      - name: Commit new posts and site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts
          git add _site
          git commit -m "Auto: Update content and site" || echo "No changes to commit"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
